name: Deploy Dev Branch to Second Repo

on:
  push:
    branches: [ dev ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v4
      with:
        ref: dev
        fetch-depth: 0  # Fetch full history for proper git operations

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Build Jekyll site
      run: |
        bundle exec jekyll build

    - name: Deploy to second repository
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        external_repository: traillife-sc2244/traillife-sc2244-dev.github.io
        publish_branch: main  # Branch in the target repo to push to
        publish_dir: ./_site  # Jekyll builds to _site directory
        commit_message: 'Deploy from dev branch: ${{ github.sha }}'
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'